{% set name = "xq" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sibprogrammer/xq/archive/v{{ version }}.tar.gz
  sha256: 9432a992d2f0ab82a7350da6317e27f835713c340177518dd08581bd0e918365

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - xq --help

about:
  home: https://github.com/sibprogrammer/xq
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line XML and HTML beautifier and content extractor
  dev_url: https://github.com/sibprogrammer/xq

extra:
  recipe-maintainers:
    - danielnachun
