schema_version: 1

context:
  version: "1.5.1"

package:
  name: xq
  version: ${{ version }}

source:
  url: https://github.com/sibprogrammer/xq/archive/v${{ version }}.tar.gz
  sha256: d57579a6c2009f3bd0f6b6f66f12744eb895575b767e7a02a099003c6bdcda3d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - xq --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line XML and HTML beautifier and content extractor
  homepage: https://github.com/sibprogrammer/xq
  repository: https://github.com/sibprogrammer/xq

extra:
  recipe-maintainers:
    - danielnachun
