schema_version: 1

context:
  version: "1.4.0"

package:
  name: xq
  version: ${{ version }}

source:
  url: https://github.com/sibprogrammer/xq/archive/v${{ version }}.tar.gz
  sha256: 6cc922d2241e10968d8985b2a8a8abe1328d8bd0ebcf5f7741d8387022436f00

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - xq --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line XML and HTML beautifier and content extractor
  homepage: https://github.com/sibprogrammer/xq
  repository: https://github.com/sibprogrammer/xq

extra:
  recipe-maintainers:
    - danielnachun
