schema_version: 1

context:
  version: "1.5.0"

package:
  name: xq
  version: ${{ version }}

source:
  url: https://github.com/sibprogrammer/xq/archive/v${{ version }}.tar.gz
  sha256: 11420d1e4c8ac1eae0c99e33071f8f10e4c12ecd65cbffcad8a36ca65ae7134a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - xq --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line XML and HTML beautifier and content extractor
  homepage: https://github.com/sibprogrammer/xq
  repository: https://github.com/sibprogrammer/xq

extra:
  recipe-maintainers:
    - danielnachun
